### PR TITLE
Issue 15 keeping the class assigned

### PR DESCRIPTION
**Pull request by zmrhaljiri**
Feature request from https://github.com/theGC/html-webpack-inline-svg-plugin/issues/15

### CODE REVIEW

**Comment by phjardas** [comment]
How about we go one step further and simply forward _all_ attributes except `inline` and `src` to the SVG? This would allow to also set ARIA attributes for instance.

**Comment by AntonioRedondo** [comment]
No merge for this PR @theGC? These changes would be super beneficial for the plug-in. Instead now the `class` attribute has to be added inside SVG files.

**Comment by zmrhaljiri** [comment]
Thank you @phjardas for the idea, it makes perfect sense. Now, all passed attributes are set to the `<svg>` element.

**Comment by zmrhaljiri** [comment]
@theGC, is it possible to approve and merge this pull request, please?

**Comment by zmrhaljiri** [comment]
Thank you)

**Pull request merged**
