### PR TITLE
v2.3.0 changes addressing issue 27

### PR DESCRIPTION
**Pull request by AntonioRedondo**
These changes address issue https://github.com/theGC/html-webpack-inline-svg-plugin/issues/27:
* BREAKING CHANGE: On the webpack configuration file the `svgoConfig` option must now go inside `HtmlWebpackInlineSVGPlugin({})` instead of `HtmlWebpackPlugin({})`. An error is thrown at webpack build time otherwise.
* The defaults for the `svgo` module aren't hardcoded anymore and –excepting the `cleanupIDs` option– the defaults are now set by the own module `svgo` and not by `html-webpack-inline-svg-plugin`.
* `package.json` dependencies have been updated to latest versions.
* Small corrections on `README.md`.

### CODE REVIEW

**Comment by AntonioRedondo** [comment]
Merging the PR. 🤜 Comments still welcome.

**Comment by AntonioRedondo** [comment]
Merging PR. 🤜 Comments still welcome.

**Comment by AntonioRedondo** [comment]
@theGC does the package get released on npm automatically? Or do you have to press the button manually?

**Comment by theGC** [comment]
it auto publishes to npm, looks like v2.3.0 is live
https://www.npmjs.com/package/html-webpack-inline-svg-plugin

**Pull request merged**
